# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    boot = {
        extraModprobeConfig = ''
            options v4l2loopback devices=1 video_nr=1 card_label="OBS CAM" exclusive_caps=1
        '';
        extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
        initrd = {
            availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" ];
            kernelModules = [ ];
            luks = {
                devices = {
                    "encrypted" = {
                        device = "/dev/disk/by-label/encrypted";
                    };
                };
            };
        };
        kernelModules = [ "kvm-intel" ];
    };

    fileSystems = {
        "/" = {
            device = "/dev/disk/by-label/ROOT";
            fsType = "ext4";
        };
        "/boot" = {
            device = "/dev/disk/by-label/BOOT";
            fsType = "vfat";
            options = ["umask=0077"];
        };
    };
    
    hardware = {
        cpu = {
            intel = {
                updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            };
        };
    };

    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    networking = {
        useDHCP = lib.mkDefault true;
    };

    nixpkgs = {
        hostPlatform = lib.mkDefault "x86_64-linux";
    };

    swapDevices = [ ];
}
