# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    modulesPath,
    ...
}:

{
    boot = {
        extraModprobeConfig = ''
            options v4l2loopback devices=1 video_nr=1 card_label="OBS CAM" exclusive_caps=1
        '';
        extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
        initrd = {
            availableKernelModules = [
                "xhci_pci"
                "ehci_pci"
                "ahci"
                "sd_mod"
            ];
            kernelModules = [ ];
        };
        kernelModules = [ "kvm-intel" ];
    };

    hardware = {
        cpu = {
            intel = {
                updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            };
        };
    };

    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    networking = {
        useDHCP = lib.mkDefault true;
    };

    nixpkgs = {
        hostPlatform = lib.mkDefault "x86_64-linux";
    };

    swapDevices = [ ];
}
