# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    modulesPath,
    ...
}:

{
    boot = {
        extraModulePackages = [ ];
        initrd = {
            availableKernelModules = [
                "xhci_pci"
                "ahci"
                "nvme"
                "usbhid"
                "usb_storage"
                "sd_mod"
            ];
            kernelModules = [ ];
        };
        kernelModules = [
            "kvm-amd"
        ];
    };

    hardware = {
        cpu = {
            amd = {
                updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            };
        };
    };

    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    nixpkgs = {
        hostPlatform = lib.mkDefault "x86_64-linux";
    };
}
