# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    boot = {
        extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
        extraModprobeConfig = ''
            options v4l2loopback devices=1 video_nr=1 card_label="OBS CAM" exclusive_caps=1
        '';
        initrd = {
            availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
            kernelModules = [ "amdgpu" ];
            luks = {
                devices = {
                    "encrypted" = {
                        device = "/dev/disk/by-label/encrypted";
                    };
                };
            };
        };
        kernelModules = [ "kvm-intel" ];
    };

    fileSystems = {
        "/" = {
            device = "/dev/disk/by-label/ROOT";
            fsType = "ext4";
        };
        "/boot" = {
            device = "/dev/disk/by-label/BOOT";
            fsType = "vfat";
            options = ["umask=0077"];
        };
        "/home/emil/tmp" = {
            fsType = "tmpfs";
            options = [ "rw" "size=10G" "nodev" "nosuid" "noexec" "uid=1000" "gid=1000" ];
        };
        "/home/emil/docker-compose" = {
            device = "172.16.0.12:/nfs/docker/compose";
            fsType = "nfs4";
            options = [ "rw" "x-systemd.automount" "noauto" ];
        };
        "/home/emil/Manga" = {
            device = "172.16.0.12:/nfs/Manga";
            fsType = "nfs4";
            options = [ "rw" "x-systemd.automount" "noauto" ];
        };
        "/home/emil/Media" = {
            device = "172.16.0.12:/nfs/Media";
            fsType = "nfs4";
            options = [ "rw" "x-systemd.automount" "noauto" ];
        };
        "/home/emil/roms" = {
            device = "172.16.0.12:/nfs/ROMS";
            fsType = "nfs4";
            options = [ "rw" "x-systemd.automount" "noauto" ];
        };
    };

    hardware = {
        cpu = {
            intel = {
                updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            };
        };
    };

    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    networking = {
        useDHCP = lib.mkDefault true;
    };

    nixpkgs = {
        hostPlatform = lib.mkDefault "x86_64-linux";
    };

    swapDevices = [ ];
}
